### ISSUE TITLE
Hardcode table for "fridge_item"

### ISSUE THREAD

**Issue by ArmanAli05** [JoshuaRaybould/SSH#26]
Starting to hardcode the ingredients needed. I'm also just thinking that there should be some items which won't be stored in the fridge but we must always assume that the user has (like cooking oil or bread perhaps). If you have any ideas of items like that let me know.

**Comment by ArmanAli05** [comment]
Also, are we having eggs as one item or is a 6 pack and 12 pack eggs different?

**Comment by JoshuaRaybould** [comment]
I think it would be simpler to have eggs as one item since it's easier to connect the recipe to that rather than connecting it to both a 6 pack and 12 pack. I guess the quantity in the tenants_fridge_items table would be based on pack size when they first put it in the fridge. Reading the example in the assignment it says: "SSH Camera can provide detailed information about the contents of the fridge, including quantities" so i think this should be fine.
