### ISSUE TITLE
Started Quality calculation logic

### ISSUE THREAD

**Issue by varsityyy** [JoshuaRaybould/SSH#27]
Made 2 classes, ingredients and recipes, started implementing the ingredients class

**Comment by JoshuaRaybould** [comment]
I think for the quality you just want to focus on the ingredients. Are you writing a function to calculate qualiy for an item given the relevant data or what is the plan for this part?

I think as part of this too since we are imagining quality is calculated when added and then daily, we will need a way to go through all the items every tenant has and update the quality value (to mimic the daily job, although this isn't that important for now)

**Comment by varsityyy** [comment]
Yes, my function will calculate the  quality based on the relevant data.

And about your second point, i agree, I'd need to find a way to store all the ingredients for each tenant, then iterate through all tenants, and finally update the quality of the ingredient.

**Comment by JoshuaRaybould** [comment]
Sounds good!

**Comment by varsityyy** [comment]
Update on my unit, Implemented the ingredients class as well as made some basic tests for it, still handling some errors but the code is pretty much done.
