### ISSUE TITLE
Recipes in JSON file

### ISSUE THREAD

**Issue by benjoseph05** [JoshuaRaybould/SSH#76]
Are we saying to present the hardcoded recipes in the format of recipe name, recipe instructions, recipe ingredients and recipe quality  (basically how it is hardcoded in the loadrecipe class) in a JSON file. And then would that mean that rather than my recipe matching method call the return recipes method which returns all the hardcoded recipes - it would instead have to retrieve the recipes from the JSON file?

**Comment by JoshuaRaybould** [comment]
That sounds correct yes although I am not totally familiar with JSON and so make whatever choices make sense to you so that you can get the data out properly. From what I've looked at it doesn't seem like getting data out of it would be too difficult, I think the jackson dependency is meant to make it easier but have you looked into this?

**Comment by JoshuaRaybould** [comment]
Any updates on this?

**Comment by benjoseph05** [comment]
I have added a json dependency to the dependencies of the build.gradle file

**Comment by benjoseph05** [comment]
I have created a JSON file which has the recipes in JSON format. I have also added a method that takes in the JSON file as input and outputs an array list of recipes and it seems to work well with the recipe matching method. Should be ready to push into main branch.

**Comment by JoshuaRaybould** [comment]
Sounds good, create a pull request when you're ready.

**Comment by benjoseph05** [comment]
sent pull request
